sudo: false
language: python
python:
  - 3.8
matrix:
  include:
    - python: 3.8
      dist: xenial
install:
  - pip install poetry
  - poetry install -vvv
script:
#  - python test_mubu_login.py
  - coverage run --source=test_mubu_login -m unittest discover
  - coverage report
after_success:
  - poetry run coveralls